"""Static thumbnail co-located with a workflow's preview.gif.

Stored at <workflow_folder>/preview_thumb.webp (or .png if the Qt build
lacks WEBP). Generated at 512x512
with KeepAspectRatioByExpanding + center-crop (same logic as
_cached_pixmap in library_panel.py for static images).

Sync rules with preview.gif:
  - gif present, thumb missing or older than gif (mtime) -> regenerate
  - gif absent (user removed or replaced with static image), thumb still
    present                                              -> delete thumb
  - workflow folder not writable (Shared mount, perm denial)
                                                         -> skip silently,
                                                            no fallback

Generated by Workflow Editor at save time and by Library refresh in
background via ThumbnailWorker.
"""

import errno
import logging
import os

from Nukomfy.utils.qt_compat import QtCore, QtGui

_log = logging.getLogger(__name__)

THUMB_MAX_PX = 512
THUMB_QUALITY = 85


def _detect_format():
    """Resolve the thumbnail image format once. WEBP is preferred (small,
    good quality); on a Qt build whose imageformats lack the webp plugin
    (rare, standard Nuke bundles it) fall back to PNG so the write still
    succeeds, honoring the documented .webp/.png contract. Defaults to
    WEBP when probing is unavailable (e.g. no QApplication yet)."""
    try:
        fmts = {bytes(f).lower()
                for f in QtGui.QImageWriter.supportedImageFormats()}
        return ('WEBP', '.webp') if b'webp' in fmts else ('PNG', '.png')
    except Exception:
        return 'WEBP', '.webp'


_FORMAT, _EXT = _detect_format()
_BASENAME = 'preview_thumb' + _EXT      # slot 1 (primary preview.*)
_BASENAME_B = 'preview_b_thumb' + _EXT  # slot 2 (optional preview_b.*)

# errno values that indicate "the folder is read-only / not ours to touch".
# Library refresh hits these on Shared mounts even after is_writable() passed
# (Windows access masks lie on network drives). Silent skip - the folder
# doesn't belong to us, the warning would just spam the console each refresh.
_READONLY_ERRNOS = frozenset((errno.EACCES, errno.EPERM, errno.EROFS))


def thumb_path_for(folder, basename=_BASENAME):
    """Return the absolute path where the thumb would live (regardless of
    whether the file currently exists)."""
    return os.path.join(folder, basename)


def existing_thumb(folder, basename=_BASENAME):
    """Return the path to the thumb file if present, else None."""
    p = os.path.join(folder, basename)
    return p if os.path.isfile(p) else None


def needs_regeneration(folder, gif_path, basename=_BASENAME):
    """True iff gif_path exists and the thumb is missing or older."""
    if not gif_path or not os.path.isfile(gif_path):
        return False
    thumb = existing_thumb(folder, basename)
    if thumb is None:
        return True
    try:
        return os.stat(thumb).st_mtime_ns < os.stat(gif_path).st_mtime_ns
    except OSError:
        return True


def needs_deletion(folder, has_gif, basename=_BASENAME):
    """True iff a thumb is present but no gif backs it (orphan)."""
    return (not has_gif) and (existing_thumb(folder, basename) is not None)


def is_writable(folder):
    """Cheap pre-flight check before scheduling a write. Shared mounts
    and read-only permission cases return False so we skip silently."""
    try:
        return os.access(folder, os.W_OK)
    except OSError:
        return False


def _square_crop_pixmap(pixmap, size_px):
    """Scale pixmap to size_px x size_px using KeepAspectRatioByExpanding +
    center-crop. Mirrors _cached_pixmap in library_panel.py:90-108."""
    px = pixmap.scaled(size_px, size_px,
                       QtCore.Qt.KeepAspectRatioByExpanding,
                       QtCore.Qt.SmoothTransformation)
    if px.width() > size_px or px.height() > size_px:
        x = (px.width() - size_px) // 2
        y = (px.height() - size_px) // 2
        px = px.copy(x, y, size_px, size_px)
    return px


def _square_crop_image(image, size_px):
    """QImage variant of _square_crop_pixmap, safe to run off the GUI
    thread (QImage, unlike QPixmap, is not GUI-thread-bound)."""
    im = image.scaled(size_px, size_px,
                      QtCore.Qt.KeepAspectRatioByExpanding,
                      QtCore.Qt.SmoothTransformation)
    if im.width() > size_px or im.height() > size_px:
        x = (im.width() - size_px) // 2
        y = (im.height() - size_px) // 2
        im = im.copy(x, y, size_px, size_px)
    return im


def render_first_frame(gif_path):
    """Decode first frame of a GIF as a QImage at THUMB_MAX_PX square,
    center-cropped. Returns None on failure. Stays in QImage so it is safe
    to run off the GUI thread (QPixmap is GUI-thread-only). Each call uses
    its own QImageReader instance."""
    reader = QtGui.QImageReader(gif_path)
    reader.setDecideFormatFromContent(True)
    if not reader.canRead():
        return None
    img = reader.read()
    if img.isNull():
        return None
    return _square_crop_image(img, THUMB_MAX_PX)


def write_thumb(folder, pixmap, basename=_BASENAME):
    """Atomic write of pixmap (a QPixmap or QImage) as preview_thumb in folder.

    Uses tempfile + os.replace so concurrent workers can't observe a
    half-written file. Returns True on success, False on graceful
    failure (caller falls back to inline QMovie decode).

    Caller should pre-check is_writable(folder) - this still degrades
    gracefully on permission denial.
    """
    final = thumb_path_for(folder, basename)
    tmp = final + '.tmp'
    try:
        if not pixmap.save(tmp, _FORMAT, THUMB_QUALITY):
            try:
                os.remove(tmp)
            except OSError:
                pass
            return False
        os.replace(tmp, final)
        return True
    except OSError as e:
        if e.errno not in _READONLY_ERRNOS:
            _log.warning(
                'Preview thumbnail write failed at %s: %s', folder, e)
        try:
            os.remove(tmp)
        except OSError:
            pass
        return False


def delete_thumb(folder, basename=_BASENAME):
    """Remove the preview_thumb file in folder. Silent on failure."""
    p = os.path.join(folder, basename)
    if not os.path.isfile(p):
        return True
    try:
        os.remove(p)
        return True
    except OSError as e:
        if e.errno not in _READONLY_ERRNOS:
            _log.warning(
                'Preview thumbnail delete failed at %s: %s', p, e)
        return False


# Static-image extensions that we re-encode at workflow save time.
# GIFs are excluded because Qt has no native multi-frame GIF encoder
# and we don't pull in PIL.
_STATIC_FORMAT_BY_EXT = {
    '.png':  'PNG',
    '.jpg':  'JPG',
    '.jpeg': 'JPG',
    '.webp': 'WEBP',
}


def resize_static_preview(src_path, dest_path):
    """Re-encode a static preview image into a THUMB_MAX_PX square at
    dest_path, using KeepAspectRatioByExpanding + center crop (same
    framing as the co-located preview_thumb).

    Returns True on success. Returns False when:
      - the destination extension is not a supported static format
        (caller falls back to a raw copy, GIFs go through this branch)
      - the source image fails to load
      - QPixmap.save() reports failure (e.g. WEBP plugin missing for a
        .webp destination)

    Quality 95 for lossy formats; PNG uses Qt's default.
    """
    ext = os.path.splitext(dest_path)[1].lower()
    fmt = _STATIC_FORMAT_BY_EXT.get(ext)
    if not fmt:
        return False
    src = QtGui.QPixmap(src_path)
    if src.isNull():
        return False
    pix = _square_crop_pixmap(src, THUMB_MAX_PX)
    quality = -1 if fmt == 'PNG' else 95
    try:
        return bool(pix.save(dest_path, fmt, quality))
    except OSError as e:
        if e.errno not in _READONLY_ERRNOS:
            _log.warning(
                'Preview resize save failed at %s: %s', dest_path, e)
        return False
    except Exception as e:
        _log.warning(
            'Preview resize save failed at %s: %s', dest_path, e)
        return False
